package Principal;
import Insertar.*;
import Listar.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_consultar_celulares_principal = new javax.swing.JButton();
        btn_insertar_usuarios_principal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_salir_principal = new javax.swing.JButton();
        btn_consultar_usuarios_principal1 = new javax.swing.JButton();
        btn_consultar_usuarios_principal2 = new javax.swing.JButton();
        btn_consultar_usuarios_principal3 = new javax.swing.JButton();
        btn_consultar_usuarios_principal4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Welcome"));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        jLabel1.setToolTipText("qw");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(114, 14));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Escoja una de las opciones");

        btn_consultar_celulares_principal.setBackground(new java.awt.Color(255, 0, 51));
        btn_consultar_celulares_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar_celulares_principal.setText("2 - Consultar Celular");
        btn_consultar_celulares_principal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_consultar_celulares_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_celulares_principalActionPerformed(evt);
            }
        });

        btn_insertar_usuarios_principal.setBackground(new java.awt.Color(255, 0, 51));
        btn_insertar_usuarios_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_insertar_usuarios_principal.setText("1 - Ingresar Celular");
        btn_insertar_usuarios_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertar_usuarios_principalActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_salir_principal.setBackground(new java.awt.Color(255, 0, 51));
        btn_salir_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir_principal.setText("SALIR");
        btn_salir_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_principalActionPerformed(evt);
            }
        });

        btn_consultar_usuarios_principal1.setBackground(new java.awt.Color(255, 0, 51));
        btn_consultar_usuarios_principal1.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar_usuarios_principal1.setText("3 - Crear Usuario");
        btn_consultar_usuarios_principal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_usuarios_principal1ActionPerformed(evt);
            }
        });

        btn_consultar_usuarios_principal2.setBackground(new java.awt.Color(255, 0, 51));
        btn_consultar_usuarios_principal2.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar_usuarios_principal2.setText("4 - Ver Usuarios");
        btn_consultar_usuarios_principal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_usuarios_principal2ActionPerformed(evt);
            }
        });

        btn_consultar_usuarios_principal3.setBackground(new java.awt.Color(255, 0, 51));
        btn_consultar_usuarios_principal3.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar_usuarios_principal3.setText("4 - Ver Usuarios");
        btn_consultar_usuarios_principal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_usuarios_principal3ActionPerformed(evt);
            }
        });

        btn_consultar_usuarios_principal4.setBackground(new java.awt.Color(255, 0, 51));
        btn_consultar_usuarios_principal4.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar_usuarios_principal4.setText("4 - Ver Usuarios");
        btn_consultar_usuarios_principal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_usuarios_principal4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(184, 184, 184))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(247, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_salir_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultar_usuarios_principal2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultar_usuarios_principal1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultar_usuarios_principal3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_insertar_usuarios_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultar_celulares_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultar_usuarios_principal4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_insertar_usuarios_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultar_celulares_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultar_usuarios_principal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultar_usuarios_principal2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultar_usuarios_principal3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultar_usuarios_principal4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_salir_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consultar_celulares_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_celulares_principalActionPerformed
        try {
            Listar vistaListar_Celulares = new Listar_Usuarios();
            vistaListar_Celulares.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_consultar_celulares_principalActionPerformed

    private void btn_insertar_usuarios_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertar_usuarios_principalActionPerformed
        Insertar vistaInsertar = new Insertar();
        vistaInsertar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_insertar_usuarios_principalActionPerformed

    private void btn_salir_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_principalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salir_principalActionPerformed

    private void btn_consultar_usuarios_principal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_usuarios_principal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar_usuarios_principal1ActionPerformed

    private void btn_consultar_usuarios_principal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_usuarios_principal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar_usuarios_principal2ActionPerformed

    private void btn_consultar_usuarios_principal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_usuarios_principal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar_usuarios_principal3ActionPerformed

    private void btn_consultar_usuarios_principal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_usuarios_principal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar_usuarios_principal4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar_celulares_principal;
    private javax.swing.JButton btn_consultar_usuarios_principal1;
    private javax.swing.JButton btn_consultar_usuarios_principal2;
    private javax.swing.JButton btn_consultar_usuarios_principal3;
    private javax.swing.JButton btn_consultar_usuarios_principal4;
    private javax.swing.JButton btn_insertar_usuarios_principal;
    private javax.swing.JButton btn_salir_principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
